services:
  story-engine-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-engine-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config.docker.json:/app/config.docker.json
    environment:
      - GAME_CONFIG=/app/config.docker.json
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - story-engine-network

  story-engine-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-engine-worker
    command: ["./worker"]  # Override CMD
    volumes:
      - ./data:/app/data
      - ./config.docker.json:/app/config.docker.json
    environment:
      - GAME_CONFIG=/app/config.docker.json
      - WORKER_ID=worker-1
    depends_on:
      - redis
    networks:
      - story-engine-network
    restart: unless-stopped

  # ollama:
  #     image: ollama/ollama
  #     container_name: ollama
  #     ports:
  #       - "11434:11434"         # Exposes Ollama's HTTP API
  #     volumes:
  #       - ollama_data:/root/.ollama
  #     environment:
  #       - OLLAMA_MODELS=/root/.ollama/models
  #     healthcheck:
  #       test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11434/"]
  #       interval: 15s
  #       timeout: 10s
  #       retries: 3
  #       start_period: 60s
  #     networks:
  #       - story-engine-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - story-engine-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_LEVEL: "debug"
    networks:
      - story-engine-network

# Ollama data volume to persist models and configurations
# volumes:
  # ollama_data:

networks:
  story-engine-network:
    driver: bridge
