services:
  roleplay-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roleplay-agent
    ports:
      - "8080:8080"
    environment:
      - ROLEPLAY_CONFIG=/app/config.docker.json
    depends_on:
      - ollama
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - roleplay-network

  ollama:
      image: ollama/ollama
      container_name: ollama
      ports:
        - "11434:11434"         # Exposes Ollama's HTTP API
      volumes:
        - ollama_data:/root/.ollama
      environment:
        - OLLAMA_MODELS=/root/.ollama/models
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11434/"]
        interval: 15s
        timeout: 10s
        retries: 3
        start_period: 60s
      networks:
        - roleplay-network

  redis:
    image: redis:7-alpine
    container_name: roleplay-redis
    ports:
      - "6379:6379"
    networks:
      - roleplay-network

# Ollama data volume to persist models and configurations
volumes:
  ollama_data:

networks:
  roleplay-network:
    driver: bridge
